### ISSUE TITLE
Camera doesn't work on Pixel 3a

### ISSUE THREAD

**Issue by pallinko** [FuriLabs/furi-images#1]
Camera doesn't work on Pixel 3a.  droidian-OFFICIAL-phosh-phone-google_sargo-api28-arm64-nightly_20240318.zip

**Comment by pallinko** [comment]
I flashed the droid image and the camera works without problems

**Comment by FakeShell** [comment]
these images are not supposed to be used on other devices. all of these devices will soon be dropped in favor of our own device which is the FuriLabs FLX1.
feel free to switch to https://github.com/droidian-images/droidian
closing
